### PR TITLE
Fix #206 Convert protobuf field names to camel case

### LINKED ISSUE #206: Fails to map protobuf fields with underscores
The [Google Protobuf Style Guide](https://developers.google.com/protocol-buffers/docs/style) states that multi-word fields use a lowercase-underscore naming pattern.

The tests for Dozer proto use camelcase instead, see: [ProtoTestObjects.proto](https://github.com/DozerMapper/dozer/blob/master/proto/src/test/java/org/dozer/vo/proto/ProtoTestObjects.proto).

When the Google suggested lowercase-underscore pattern is used, Dozer fails to find the property to write to, "unable to determine write method…". The workaround is to use only single word fields or use camelcase for field names. But Dozer should be able to work with `.proto` files conforming to the style guide.

### PR DESCRIPTION
**Pull request by jbq**
Requires to merge #411 first

### CODE REVIEW

**Comment by garethahealy** [comment]
https://github.com/DozerMapper/dozer/issues/206

**Comment by garethahealy** [comment]
@jbq ; please rebase

File: proto/src/main/java/org/dozer/util/ProtoUtils.java [hunk 1]
```diff
@@ -66,18 +69,28 @@ private ProtoUtils() {
 
         Descriptors.FieldDescriptor foundDescriptor = null;
         for (Descriptors.FieldDescriptor descriptor : protoFieldDescriptors) {
-            if (fieldName.equals(descriptor.getName())) {
+            if (sameField(fieldName, descriptor.getName())) {
+                // XXX comment why return not done immediately at first match
```
Comment (garethahealy) [inline proto/src/main/java/org/dozer/util/ProtoUtils.java]: As per your comment, why isnt there a break here?

File: proto/pom.xml [hunk 2]
```diff
@@ -44,6 +44,12 @@
             <groupId>com.google.protobuf</groupId>
             <artifactId>protobuf-java</artifactId>
         </dependency>
+
+        <dependency>
+            <groupId>com.google.guava</groupId>
+            <artifactId>guava</artifactId>
+            <version>22.0</version>
+        </dependency>
     </dependencies>
```
Comment (garethahealy) [inline proto/pom.xml]: Can you add this to bom-dependancies dependencyManagement [1] block please, making sure its in alphabetical order. You don't need to have the version specified here then - just like how the plugins work.

[1] https://github.com/DozerMapper/dozer/blob/master/bom-dependencies/pom.xml#L58

File: proto/src/main/java/org/dozer/util/ProtoUtils.java (hunk 1 above)
Comment (jbq) [inline proto/src/main/java/org/dozer/util/ProtoUtils.java]: I put this comment because I was wondering why it wasn't done in the first place.  Is there a good reason?  Seems awkward to me.  I can add a `break` if you think likewise.

**Comment by garethahealy** [comment]
@jbq ; added a few comments.

@orange-buffalo ; can you also review please.

File: proto/src/main/java/org/dozer/util/ProtoUtils.java (hunk 1 above)
Comment (garethahealy) [inline proto/src/main/java/org/dozer/util/ProtoUtils.java]: I cant see why there wouldnt be a break. Please add and retest.

Comment (jbq) [inline proto/src/main/java/org/dozer/util/ProtoUtils.java]: done

File: proto/pom.xml [hunk 3]
```diff
@@ -44,6 +44,11 @@
             <groupId>com.google.protobuf</groupId>
             <artifactId>protobuf-java</artifactId>
         </dependency>
+
+        <dependency>
+            <groupId>com.google.guava</groupId>
```
Comment (orange-buffalo) [inline proto/pom.xml]: Ideally, dependencies in this section should be also sorted alphabetically.
